contact_links:
    - name: Questions and Help
      url: https://github.com/codeitcodes/codeit/discussions/categories/q-a
      about: This issue tracker is not for support questions. Please refer to Codeit's Discussion tab.
