[[redirects]]
  from = "https://cde.run"
  to = "https://codeit.codes/full"
  status = 301
  force = true

[[redirects]]
  from = "https://dev.cde.run"
  to = "https://dev.codeit.codes/full"
  status = 301
  force = true

[[redirects]]
  from = "https://dev.codeit.codes"
  to = "https://dev.codeit.codes/full"
  status = 301
  force = true
